import { Box } from '@mui/material'
import type { Metadata } from 'next'
import { getLocale } from 'next-intl/server'
import { type PropsWithChildren } from 'react'
import Providers from '../providers/providers'
import { pretendard } from '../utils'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export const viewport = {
  width: 1
}

const RootLayout = async ({ children }: Readonly<PropsWithChildren>) => {
  const locale = await getLocale()

  return (
    <Box component='html' lang={locale}>
      <Box
        component='body'
        sx={{
          bgcolor: 'base.bg'
        }}
        className={pretendard.className}
      >
        <Providers>{children}</Providers>
      </Box>
    </Box>
  )
}

export default RootLayout
