import { Box } from '@mui/material';
import type { Metadata } from 'next';
import { getLocale } from 'next-intl/server';
import { type PropsWithChildren } from 'react';
import { Typography } from '../components';
import Providers from '../providers/providers';
import { roboto } from '../utils';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const viewport = {
  width: 1,
};

export default async function RootLayout({
  children,
}: Readonly<PropsWithChildren>) {
  const locale = await getLocale();

  return (
    <Box component="html" lang={locale}>
      <Box component="body" className={roboto.className}>
        <Typography>hello</Typography>

        <Providers>{children}</Providers>
      </Box>
    </Box>
  );
}
